### ISSUE TITLE
作为客人，我希望通过船屋网站进行下单，以便可以让我享受地道的苏格兰美食

### ISSUE THREAD

**Issue by pipin** [idcf-boat-house/boat-house#114]
AC:

1. Client端加入用户点餐功能，可以通过客户端选择菜品并一键下单(不需要实现订单支付)，用户下单完成后需支持补充菜品功能。
2. Management端加入用户在线点餐管理功能，能够让后台管理员查看到用户下单信息，并及时将订单状态信息反馈给客户。
3. 订单服务相关API接口

**Comment by zlweicoder** [comment]
@pipin 老师跟您确认下，这个US是否将订单管理功能和支付功能都包含？因为AC1中的描述有些模糊不清。如果已经包含，是否需要单独拆分出支付功能的US？

**Comment by pipin** [comment]
不包含支付功能，等完成这个功能后，再实现订单线上支付功能
