### ISSUE TITLE
关于代码仓库的使用问题

### ISSUE THREAD

**Issue by yimeng** [idcf-boat-house/boat-house#127]
product-service/api/src/test/java/com/idcf/boathouse/chromedriver.exe 7.4M 
1. 还嫌github clone速度不够慢吗？需要仔细审视下二进制大文件的必要性，不要给团队其它人带来不必要的麻烦。
2. git不是用来存储二进制文件的 ，如果要用二进制大文件请使用Git LFS。
3. 希望在代码review的时候能有一个稍微严格的标准，一些不良的git使用习惯在review能严格控制下。
4. exe文件在mac上并不能使用，需要编写代码的时候需要注意下平台的通用性。建议机器上的可执行文件就好了。
5. 另外建议使用chrome的headless功能，在CI机器上开一个chrome，然后把--remote-debugging-port=9222 开放就ok。这样也可以避免测试client不一致导致的问题。

**Comment by zhouwenyang** [comment]
@yimeng 感谢您的建议，您的建议非常好，我们这边将会写一个关于仓库提交的一些规范。
