### ISSUE TITLE
boathouse_statistics-service-worker_1 这个服务占用系统资源太大

### ISSUE THREAD

**Issue by yimeng** [idcf-boat-house/boat-house#132]
d36015101cf1        boathouse_statistics-service-worker_1   101.43%             23.05MiB / 7.778GiB   0.29%               28.8MB / 28.1MB     0B / 0B             23

MacBook Pro (16-inch, 2019) 2.3 GHz 八核Intel Core i9 64 GB 2667 MHz DDR4
风扇狂转，我限制docker只使用2核还是狂转。这个服务启动的时候在干嘛？要用这么大的CPU

**Comment by yimeng** [comment]
看不懂.net代码，但是感觉如下语句有没有keep间隔时间，如果间隔时间很短。确实很容器烧CPU
···            
keepAliveCommand.CommandText = "SELECT 1";
···

**Comment by yimeng** [comment]
https://github.com/npgsql/npgsql/issues/1214
as a workaround you may want to set a timeout (e.g. 20 seconds) and then manually send a keepalive (SELECT 1).

 set a timeout (e.g. 20 seconds) ！！！！！
好像代码中没有看到有timeout 不太会.net代码 要不就改了。

**Comment by zhouwenyang** [comment]
@yimeng 这个是个问题。这个worker是持续的循环拉取redis里的数据，然后扔到mysql里。
其实这个逻辑不是特别重要。可以把时间设置的长一点，这样性能会有所缓解。

@WalkerLu @zlweicoder @dengyakui

**Comment by zhouwenyang** [comment]
@yimeng 
感谢你的建议，我们已经把时间改为10s统计一次。cpu已经掉下来了
![image](https://user-images.githubusercontent.com/6780666/76144776-92baf480-60be-11ea-97a7-79f6e369b97e.png)
