### ISSUE TITLE
作为PR提交者，我不想每次对Jenkinsfile等配置文件每次提交PR时都修改

### ISSUE THREAD

**Issue by zhouwenyang** [idcf-boat-house/boat-house#133]
作为PR提交者，我不想每次对Jenkinsfile等配置文件每次提交PR时都修改

**Comment by dengyakui** [comment]
根据这篇文档，应该可以用全局变量的方式实现
https://tomd.xyz/jenkins-env-vars/

**Comment by zhouwenyang** [comment]
@dengyakui ok我研究下
