### ISSUE TITLE
BoatHouse 二期 - 示例环境部署

### ISSUE THREAD

**Issue by ups216** [idcf-boat-house/boat-house#14]
配合 https://boat-house.cn 我们需要提供一套可用的环境

以下只是示例，我们需要把boat house的所有系统都部署一套，并通过主站作为入口，允许社区的任何人都进去访问（后台管理系统提供只读访问）

比如：
https://shop.boat-house.cn
https://admin.boat-house.cn
https://swagger.boat-house.cn
https://tools-jenkins.boat-house.cn
https://toos-nexus.boat-house.cn
https://tools-k8s.boat-house.cn
https://tools-sona.boat-house.cn

@liminany @smallidea 你们一起规划一下，需要的收找 @zhouwenyang

**Comment by smallidea** [comment]
## Web
http://application.boat-house.cn:5000 client
http://application.boat-house.cn:5001 manager
http://application.boat-house.cn:6001 statistics_service_api
http://application.boat-house.cn:7001 product_service_api
http://application.boat-house.cn:7002 account_service_api

## k8s
http://tools-k8s.boat-house.cn

## tools
http://tools-jenkins.boat-house.cn
http://tools-nexus.boat-house.cn
http://tools-sona.boat-house.cn
http://tools-jira.boat-house.cn

 **域名规划如上所示，看看这样规划是否可行
@ups216 @liminany**

待解决问题：
1. 使用https（没必要了吧？）
2. 域名映射到端口（目前web采用域名加端口形式，nexus、sona采用跳转形式）,子域名绑定同一IP的不同端口，需借助ngix,稍有点麻烦，不太好搞

**Comment by smallidea** [comment]
1. services 站点无法访问
2. 要有swagger域名对应到services
3. http://application.boat-house.cn:5000/#/ 这个网页上点了菜品的“好吃”按钮没有反应
4. http://tools-nexus.boat-house.cn/ 打不开
5. http://tools-k8s.boat-house.cn/ 打不开
6. boat-house.cn上之放主库的链接，即 https://github.com/idcf-boat-house/boat-house

**Comment by liminany** [comment]
下面两个地址可以访问：
http://application.boat-house.cn:7001/api/v1.0/orders/pending
http://application.boat-house.cn:7001/api/v1.0/swagger-ui.html

**Comment by smallidea** [comment]
前端（client、manager） appllication：5001，application：5000

**Comment by liminany** [comment]
> 1. services 站点无法访问
> 2. 要有swagger域名对应到services
> 3. http://application.boat-house.cn:5000/#/ 这个网页上点了菜品的“好吃”按钮没有反应
> 4. http://tools-nexus.boat-house.cn/ 打不开
> 5. http://tools-k8s.boat-house.cn/ 打不开
> 6. boat-house.cn上之放主库的链接，即 https://github.com/idcf-boat-house/boat-house

1.  services 站点访问地址： http://application.boat-house.cn:7001/api/v1.0/swagger-ui.html
2. swagger域名对应如下：
       - swagger-product.boat-house.cn 跳转至：http://application.boat-house.cn:7001/api/v1.0/swagger-ui.html， 目前可访问
       - swagger-account.boat-house.cn 跳转至：http://application.boat-house.cn:7002/api/v1.0/swagger-ui.html， 此地址目前不可访问
       - swagger-statistics.boat-house.cn 跳转至：http://application.boat-house.cn:6002/api/v1.0/swagger-ui.html， 此地址目前不可访问
3. 可能是应用本身没配对，比如后端API地址不对
4. 可以打开了
5. http://tools-k8s.boat-house.cn/ ,是不是本身就打不开的？
6. 正在修复

**Comment by liminany** [comment]
因上昨天域名绑定的是boathouse dev环境的IP，现在要再调整一下，现在域名规划如下：

### 开发环境
dev.boat-house.cn:xxxx

### 测试环境
test-frontend.boat-house.cn:5000
test-mgr.boat-house.cn:5001
test-product-api.boat-house.cn:7001
test-account-api.boat-house.cn:7002
test-statistics-api.boat-house.cn:6001
test-product-swagger.boat-house.cn, url跳转
test-account-swagger.boat-house.cn, url跳转
test-statistics-swagger.boat-house.cn, url跳转

/*
account-service-api         LoadBalancer   10.0.120.66    13.76.0.192     7002:32528/TCP   91d
client                      LoadBalancer   10.0.137.5     52.237.73.101   5000:30527/TCP   112d
management                  LoadBalancer   10.0.100.186   13.76.34.0      5001:32026/TCP   112d
product-service-api         LoadBalancer   10.0.164.171   52.237.77.228   8080:32159/TCP   112d
*/

### 生产环境
prod-frontend.boat-house.cn:5000
prod-mgr.boat-house.cn:5001
prod-product-api.boat-house.cn:7001
prod-account-api.boat-house.cn:7002
prod-statistics-api.boat-house.cn:6001
prod-product-swagger.boat-house.cn, url跳转
prod-account-swagger.boat-house.cn, url跳转
prod-statistics-swagger.boat-house.cn, url跳转

/*
account-service-api         LoadBalancer   10.0.95.70     52.163.48.36     7002:32192/TCP   91d
client                      LoadBalancer   10.0.245.18    52.230.122.174   5000:30707/TCP   112d
management                  LoadBalancer   10.0.193.206   52.237.72.61     5001:30086/TCP   112d
product-service-api         LoadBalancer   10.0.138.18    13.76.5.126      8080:30136/TCP   112d
*/


目前 account / statistics服务外网访问端口未打开，需在azure上打开

@ups216

**Comment by liminany** [comment]
剩下的工作：
- [x] boathouse 相关云资源成本规划
- [x] boathouse 相关环境订阅迁移所需文档链接整理
- [x] k8s集群从国际版迁移到国内版
- [x] 工具链从国际版迁移到国内版
  - [x] 安装 Jenkins,  Agent, Sonar, Jira, Nexus
  - [x] 配置 Jenkins,  Agent, Sonar, Jira, Nexus
  - [x] 安装及配置文档整理
- [x] Jenkins流水线
- [x] GitHub Action流水线
- [x] boat-house.cn 二级域名重定向
- [x] 前台应用点喜欢 没反应，需将应用逻辑调通（dev环境发现）
- [x] 测试环境和生产环境统计服务好像没有看到，也访问不了
- [x] 测试环境和生产环境account服务访问不了
- [ ] boat-house.cn站点上只保留github文档库的链接
- [x] 容器注册表（Azure Container Registery） 调研
- [x] Nexus 调研
- [ ] 安卓版APK传至boathouse官网(TODO：可以把apk上传到nexus中，官网下载链接指向nexus？)
- [ ] 把nginx配置文件放到配置库中，并配置成流水线
- [ ] mattermost相关环境安装及配置

**Comment by liminany** [comment]
## boathouse 相关环境订阅迁移所需文档链接整理:
- 云资源规划 [点这里](https://github.com/idcf-boat-house/boat-house/tree/master/docs/quick-start/guide/azure-vm-plan )
- 容器镜像仓库
    azure container reg(acr): 已经迁移至acr，[文档点这里](https://github.com/idcf-boat-house/boat-house/blob/master/docs/quick-start/guide/azure-acr/README.md)
   github pkg: 容量有限制 ,建议选择 acr, [文档点这里](https://github.com/idcf-boat-house/boat-house/blob/master/docs/quick-start/guide/azure-acr/README.md)
- 虚拟机创建：[点这里](https://github.com/idcf-boat-house/boat-house/blob/master/docs/quick-start/guide/azure-vm/readme.md)  （内部网络组网方式待补充）
- 虚拟机基本运行环境：[点这里](https://github.com/idcf-boat-house/boat-house/blob/master/docs/quick-start/operation/team-env-config.md) 和 [账号密码点这里](https://github.com/idcf-boat-house/secret-files/blob/master/environment/readme.md)
- devops相关工具部署：[团队上手指南](https://github.com/idcf-boat-house/boat-house/blob/master/docs/quick-start/operation/team-quick-start.md)
	- jenkins 及 slave: [点这里](https://github.com/idcf-boat-house/boat-house/blob/master/docs/quick-start/operation/team-env-config.md)
	- jira: [点这里](https://github.com/idcf-boat-house/boat-house/blob/master/docs/quick-start/guide/jira-deploy/readme.md)
	- Nexus: [点这里](https://github.com/idcf-boat-house/boat-house/blob/master/docs/quick-start/operation/team-env-config.md) 和 [这里](https://github.com/idcf-boat-house/boat-house/blob/master/docs/quick-start/guide/nexus-deploy/Readme.md) [这里](https://github.com/idcf-boat-house/boat-house/blob/master/docs/quick-start/guide/nexus-guide/Readme.md)
	- sonarqube: [点这里](https://github.com/idcf-boat-house/boat-house/blob/master/docs/quick-start/guide/sonarqube/Readme.md)
- k8s 群集创建及基础环境配置: [这里](https://github.com/idcf-boat-house/boat-house/blob/master/docs/quick-start/guide/k8s-azure/aks-deploy.md)和[点这里](https://github.com/idcf-boat-house/boat-house/blob/master/docs/quick-start/guide/k8s-azure/Readme.md)
- [k8s集群管理和流水线集成](https://github.com/idcf-boat-house/boat-house/blob/master/docs/quick-start/operation/team-k8s-env-config.md)

- 已经部署的工具及工具所在的vm介绍：[查看这里](https://github.com/idcf-boat-house/boat-house-infrastructure)
- boathouse 流水线集成(jenkis)：[团队上手指南-团队流水线配置](https://github.com/idcf-boat-house/boat-house/blob/master/docs/quick-start/operation/team-pipeline-config.md)
	- 前端流水线集成: [未单独写](#)
	- 后端流水线集成: [未单独写](#)
	- android客户端流水线集成: [未单独写]()

- boathouse 流水线集成(github action)：[通用文档](https://github.com/idcf-boat-house/boat-house/blob/master/docs/quick-start/guide/github-action/README.MD)
	- 前端流水线集成: [通用文档](https://github.com/idcf-boat-house/boat-house/blob/master/docs/quick-start/guide/github-action/README.MD)
	- 后端流水线集成: [通用文档](https://github.com/idcf-boat-house/boat-house/blob/master/docs/quick-start/guide/github-action/README.MD)
	- android客户端流水线集成: [通用文档](https://github.com/idcf-boat-house/boat-house/blob/master/docs/quick-start/guide/github-action/README.MD)

- boathouse 相关应用本地调试（顺便修复应用逻辑问题）
	- 前端: [仓库首页有](https://github.com/idcf-boat-house/boat-house-frontend)
	- 后端: [仓库首页有](https://github.com/idcf-boat-house/boat-house-backend)
	- 安卓端: [仓库首页有](https://github.com/idcf-boat-house/boat-house-mobile-android)
	
- boathouse 相关应用验证
	- 前端：对菜品点击"喜欢": [文档暂无，需整理]()
	- 后端：能访问api和swagger地址(account/product/Staticts)，[文档暂无，需整理]()
	- 安卓端: 目前不知道有什么联调功能，[文档暂无，需整理]()
       

@ups216 @smallidea 

待解决问题：jenkins流水线和github action流水线需要都能跑通，要评估在一套k8s中部署和运行有什么问题
update: 目前分别部署不同的命名空间中，应用本身没有问题，当使用ps脚本+vmss的方式 存在的问题是节点不够用，默认只有一个节点。如果采用aks,两个节点（b2s）目前是够用，但也有点紧张 部署时可能 会出现紧张 的情况，导致部署不成功！

## 工具指导文档

* [Selenium自动化UI测试](docs/quick-start/guide/selenium-ui-testing/Readme.md)
* [Jenkins调度Selenium](docs/quick-start/guide/selenium-for-jenkins/Readme.md)
* [Sonarqube配置指南](docs/quick-start/guide/sonarqube/Readme.md)
* [快速创建Junit测试](docs/quick-start/guide/junit-testing/Readme.md)
* [Nexus搭建指南](docs/quick-start/guide/nexus-deploy/Readme.md)
* [Nexus使用指南](docs/quick-start/guide/nexus-guide/Readme.md)
* [Postman接口测试指南](docs/quick-start/guide/postman-api-testing/Readme.md)
* [Azure快速搭建K8s环境](docs/quick-start/guide/k8s-azure/Readme.md)
* [Apollo介绍与docker部署](docs/quick-start/guide/apollo-config-center/Readme.md)
* [MetterMost OpsChat 配置](docs/quick-start/guide/chat-ops-metter-most/readme.md)
* [MetterMost OpsChat jenkins 集成](docs/quick-start/guide/chat-ops-metter-most/jenkins.md)
* [MetterMost OpsChat github 集成](docs/quick-start/guide/chat-ops-metter-most/github.md)
* [JMeter测试用例编写手册](docs/quick-start/guide/JMeter/Readme.md)
* [Jenkins集成Jmeter](docs/quick-start/guide/JMeter/jmeter--for-jenkins.md)
* [RESTful及RESTful API设计规范简介](docs/quick-start/guide/spec/restfull-api-design-spec.md)
* [k82mysql集群](docs/quick-start/guide/mysql-k8s-deploy/Readme.md)
* [使用 helm chart 部署 boat-house ](docs/quick-start/guide/k8s-helm-deploy-boat-house/README.md)
* [使用 Flyway 进行数据库持续交付](docs/quick-start/guide/java-flyway-db-pipeline/Readme.md)
* [Idea 快速创建Junit测试](docs/quick-start/guide/junit-testing/Readme.md)

**Comment by ups216** [comment]
@liminany @smallidea 另外还要确保github action也都可以正常工作，但是github action的动作和jenkins的动作有重复。你们可以考虑一下控制一下jenkins和github action的不同触发机制。

**Comment by smallidea** [comment]
需求分析：
1. 每个订阅基础费用控制在800/月以下，因为每个订阅费用为1000/月，且要保证20%的余量预防流量超标导致的费用增加；
2. 目前服务器我们均作为开发和测试用途，所以选择常规用途服务器即可。

解决方案：
一共需要3个订阅
+ 订阅1，Agent服务器，每月费用总计¥292，后续有需要可以新增到这个订阅；
+ 订阅2，工具服务器，每月费用总计¥524；
+ 订阅3，K8S，共2个节点，即2台linux虚拟机，费用合计每月¥584。

**Comment by liminany** [comment]
> @liminany @smallidea 另外还要确保github action也都可以正常工作，但是github action的动作和jenkins的动作有重复。你们可以考虑一下控制一下jenkins和github action的不同触发机制。

github action 目前调通了，不过因为k8s命令空间问题，为了避免冲突，github action 部署的k8s命令空间加了一个github，但这个命名空间不存在，所以github action会执行失败，但yml文件配置是正确的。

目前在github action的触那里加了根据每个应用或微服务的目录中来触发，比如：

push:
    paths:
      - 'src/management/**'
      - '.github/workflows/management.yml'

**Comment by ups216** [comment]
> 
> 
> 需求分析：
> 
>     1. 每个订阅基础费用控制在800/月以下，因为每个订阅费用为1000/月，且要保证20%的余量预防流量超标导致的费用增加；
> 
>     2. 目前服务器我们均作为开发和测试用途，所以选择常规用途服务器即可。
> 
> 
> 解决方案：
> 一共需要3个订阅
> 
>     * 订阅1，Agent服务器，每月费用总计¥292，后续有需要可以新增到这个订阅；
> 
>     * 订阅2，工具服务器，每月费用总计¥524；
> 
>     * 订阅3，K8S，共2个节点，即2台linux虚拟机，费用合计每月¥584。

可以，开始搞吧。

**Comment by smallidea** [comment]
@liminany 
| 用途 |  IP / DNS | 订阅 | 备注 |
| ------------- | ------------- | ------------- | ------------- |
| 工具服务器|40.73.2.216	<br/> tools.chinanorth2.cloudapp.chinacloudapi.cn | bh008 |Jenkins http://40.73.2.216:8080/<br/>Sona http://40.73.2.216:9000<br/>Jira http://40.73.2.216:7081<br/>Nexus http://40.73.2.216:8081 |
| 代理服务器 | 40.73.39.154	<br/>agent.chinanorth2.cloudapp.chinacloudapi.cn | bh102 | - |
| K8S | - | bh101 | - |

**Comment by ups216** [comment]
@smallidea 国内版的AKS产品资料和定价在这里 https://azure.microsoft.com/zh-cn/services/kubernetes-service/#pricing

**Comment by smallidea** [comment]
@ups216 @liminany 
今天遇到两个问题：
1. 原来的云资源规划不合理，今天就出现了cpu、内存、磁盘读写均居高不下的问题，所以需要把jenkins服务器中的sonar、nexus、jira独立为一个tools服务器，详情如下：

| 用途 |  IP / DNS | 订阅 | 备注 |
| ------------- | ------------- | ------------- | ------------- |
| Jenkins服务器|40.73.2.216	<br/> jenkins-new.chinanorth2.cloudapp.chinacloudapi.cn | bh102 | 包含Agent |
| Dev服务器 | 40.73.38.39  <br/>dev-new.chinanorth2.cloudapp.chinacloudapi.cn | bh102 | 与Jenkins服务器在一个局域网中 |
| 工具服务器| 40.73.33.163 <br/> tools2.chinanorth2.cloudapp.chinacloudapi.cn | bh008 | jira, sonar, nexus, nginx |
| K8S | 139.217.112.67  <br/>k8s-yuqcehkg.chinanorth2.cloudapp.chinacloudapi.cn | bh101 | - |

2.  从docker.pkg.github.com pull的时候 经常遇到断开的问题
例如：dial tcp 151.101.228.133:443: connect: connection refused
待解决

**Comment by smallidea** [comment]
> 从docker.pkg.github.com pull的时候 经常遇到断开的问题
例如：dial tcp 151.101.228.133:443: connect: connection refused
待解决

分析：github的相应域名背后是有cdn服务的，但是cdn指向的ip通常只是近一些，比如日本之类的亚洲IP，但是访问并不稳定，需要使用https://www.ipaddress.com/ 查看到对应的域名能够快速的访问的ip
解决方案：
1.  在hosts里面增加配置的方式，暂时解决了问题，很难确保后续IP是否会变动，目前在jenkins服务器和dev服务器设置如下
140.82.114.34  docker.pkg.github.com
199.232.68.133  githubusercontent.com
199.232.68.133  pkg.githubusercontent.com
140.82.112.6  api.github.com
2.  使用acr（容器注册表）的方式，即把package存储到本地的服务器，这种方式需要评估费用，并做好调试

**Comment by ups216** [comment]
@smallidea 建议把镜像直接放在 Azure Container Registery里面，这样所有环境都在一个数据中心，速度也会更快。
另外一个问题，我们所使用的各种依赖包，包括npm, maven，nuget包都可以放在nexus上。既然我们自己有了制品库就应该用起来。

**Comment by smallidea** [comment]
### 工具：
jenkins:  http://tools-jenkins.boat-house.cn
sonar:  http://tools-sonar.boat-house.cn
jira:  http://tools-jira.boat-house.cn
nexus:  http://tools-nexus.boat-house.cn
k8s master:  k8s.boat-house.cn: 指向IP: 139.217.112.67

### 开发环境
http://dev-client.boat-house.cn
http://dev-management.boat-house.cn
http://dev-product-api.boat-house.cn/api/v1.0/swagger-ui.html
http://dev-account-api.boat-house.cn/api/v1.0/swagger-ui.html
http://dev-statistics-api.boat-house.cn (停用，统计服务不需要暴露到外网）

### 测试环境
http://test-client.boat-house.cn
http://test-management.boat-house.cn
http://test-product-api.boat-house.cn/api/v1.0/swagger-ui.html
http://test-account-api.boat-house.cn/api/v1.0/swagger-ui.html
http://test-statistics-api.boat-house.cn  (停用，统计服务不需要暴露到外网）

### 生产环境
http://prod-client.boat-house.cn
http://prod-management.boat-house.cn
http://prod-product-api.boat-house.cn/api/v1.0/swagger-ui.html
http://prod-account-api.boat-house.cn/api/v1.0/swagger-ui.html
http://prod-statistics-api.boat-house.cn (停用，统计服务不需要暴露到外网）

### github action 测试环境
http://test-action-client.boat-house.cn
http://test-action-management.boat-house.cn
http://test-action-product-api.boat-house.cn/api/v1.0/swagger-ui.html
http://test-action-account-api.boat-house.cn/api/v1.0/swagger-ui.html
http://test-action-statistics-api.boat-house.cn (停用，统计服务不需要暴露到外网）

###  域名绑定原理
使用nginx反向代理的方式，跳转到指定的ip+port，比如tools-jenkins.boat-house.cn在域名解析中绑定的是Nginx所在服务器，Nginx监听http到80端口的请求，且域名为tools-jenkins.boat-house.cn，就跳转到jenkins所在的实际路径40.73.2.216:8080

### 后续工作

1. 文档完善
      - [x] 云资源规划文档调整 @smallidea  [点击](https://github.com/idcf-boat-house/boat-house/blob/master/docs/quick-start/guide/azure-vm-plan/readme.md)
      - [x] 基础设施库环境说明文档调整 @smallidea [点击](https://github.com/idcf-boat-house/boat-house-infrastructure/blob/master/README.md) 和 [账号密码](https://github.com/idcf-boat-house/secret-files/blob/master/environment/readme.md)
      - [x] boathouse 各个环境链接添加到 主库文档 @liminany 
      - [x] Nginx配置说明 @smallidea  [点击](https://github.com/idcf-boat-house/boat-house-infrastructure/blob/master/environments/nginx/readme.md)

**Comment by liminany** [comment]
> @smallidea 建议把镜像直接放在 Azure Container Registery里面，这样所有环境都在一个数据中心，速度也会更快。
> 另外一个问题，我们所使用的各种依赖包，包括npm, maven，nuget包都可以放在nexus上。既然我们自己有了制品库就应该用起来。

因为网络问题解决了，所以我们考虑先把原来的工具链及环境都调通了，然后考虑集成acr及nexus，这里面涉及到一些yml配置文件的通用化改造的问题，略麻烦
