### ISSUE TITLE
Jmeter接口测试，代理机启动的容器与Dev环境网络无法链接

### ISSUE THREAD

**Issue by zhouwenyang** [idcf-boat-house/boat-house#151]
![image](https://user-images.githubusercontent.com/6780666/76165076-13492600-618f-11ea-93ea-d4abbe0e2e43.png)

Jenkins Pipeline:
http://jenkins.devopshub.cn/blue/organizations/jenkins/boat-house/detail/master/54/pipeline/

**Comment by zhouwenyang** [comment]
@MaJie86 根据沟通建议把docker的网络链接去掉，JMX文件改用内部DNS的方式
dev：docker-server
Jenkins：jenkins-server

**Comment by barontan136** [comment]
1 已经修改网络连接参数
2 jmeter启动之前休眠80秒，等待service起来后再执行（后续可优化5s间隔check）
@zhouwenyang
