### ISSUE TITLE
作为开发人员，我希望docker-compose-template.yaml文件不要hardcode 组织

### ISSUE THREAD

**Issue by zhouwenyang** [idcf-boat-house/boat-house#155]
作为开发人员，我希望docker-compose-template.yaml文件不要hardcode 组织
以便我在提交PR的时候不需要忽略掉

AC：

1. docker-compose-template.yaml这个文件里所有的组织都使用占位符替换。
2. Jenkins流水线部署之前可以动态替换掉当前组织名称
3. 部署时可以根据自己的组织拉取镜像

**Comment by zlweicoder** [comment]
完善这个issue的小伙伴，请同步更新此文档内容：
https://github.com/idcf-boat-house/boat-house/wiki/%E5%9B%A2%E9%98%9F%E5%BC%80%E5%8F%91%E7%8E%AF%E5%A2%83%E9%83%A8%E7%BD%B2#%E5%BC%80%E5%8F%91%E7%8E%AF%E5%A2%83%E9%83%A8%E7%BD%B2%E8%84%9A%E6%9C%AC%E6%9B%BF%E6%8D%A2%E9%95%9C%E5%83%8F%E4%BB%93%E5%BA%93%E5%9C%B0%E5%9D%80

**Comment by hawaicai** [comment]
故事点 2
