### ISSUE TITLE
git仓库结构 化流程及存储库目录结构 设计

### ISSUE THREAD

**Issue by liminany** [idcf-boat-house/boat-house#17]
- [x]  设计存储库目录结构 
- [x]  规划并定制实施流程
- [x]  主库结构 整理

- [x] 基础设施库
- [x] 前端代码库
- [x] 移动端代码库
- [x] 后端代码库

@smallidea @ups216 

拆库已经完成，详见：https://github.com/idcf-boat-house/boat-house

TODO：后端单体架构流水线，可选方案：

- 将sprint boot application maven project 合并成一个Pom文件进行编译打包成一个jar
- 一个容器里面跑两个应用，需调整dockerfile,目前未完工，详见这里：https://github.com/idcf-boat-house/boat-house-backend/blob/master/src/Dockerfile

**Comment by ups216** [comment]
现有的文档可以保持原结构，确保发布到docsify以后可以正常使用即可。

**Comment by smallidea** [comment]
三个代码库的基本结构已经有了，接下来的粗略计划是

1. 前端库，可以build、test；计划耗时1d
2. android库，可以build、test；计划耗时2d
3. 后端库，参考之前的方法单体和微服务可以跑起来；计划耗时3d

**Comment by ups216** [comment]
- [x] k8s换成AKS，同时输出文档 @liminany , [文档](https://github.com/idcf-boat-house/boat-house/blob/master/docs/quick-start/guide/k8s-azure/aks-deploy.md)
- [x] k8s重复pod节点问题需要解决 @liminany 
- [x] 前端加载太慢，可能是外部CDN资源被墙的问题 @smallidea 
- [x] jenkins build里面有报错信息 @smallidea 
- [x] docker image换到azure container registry @liminany 
- [x] jira内无法创建项目 @smallidea 
- [x] 把nexus用起来，上游的包的包都拉过来，修改POM文件中包源头 @smallidea 
- [x] Jenkins WorkSpace 中的文件因为权限问题无法删除，导致Jenkins流水线报错

**Comment by smallidea** [comment]
>  前端加载太慢，可能是外部CDN资源被墙的问题 @smallidea

已资源本地话，并压缩了几张大的图片

>  jira内无法创建项目 @smallidea

jira 的站点地址需要与域名相同，因为使用了nginx

>  把nexus用起来，上游的包的包都拉过来，修改POM文件中包源头 @smallidea

npm、maven均使用了nexus（代理模式）

>  Jenkins WorkSpace 中的文件因为权限问题无法删除，导致Jenkins流水线报错

git clean 的时候没有权限，在流水线结束的时候使用sudo git clean

**Comment by ups216** [comment]
> > 前端加载太慢，可能是外部CDN资源被墙的问题 @smallidea
> 
> 已资源本地话，并压缩了几张大的图片
> 
> > jira内无法创建项目 @smallidea
> 
> jira 的站点地址需要与域名相同，因为使用了nginx
> 
> > 把nexus用起来，上游的包的包都拉过来，修改POM文件中包源头 @smallidea
> 
> npm、maven均使用了nexus（代理模式）
> 
> > Jenkins WorkSpace 中的文件因为权限问题无法删除，导致Jenkins流水线报错
> 
> git clean 的时候没有权限，在流水线结束的时候使用sudo git clean

@smallidea 资源本地化，Nginix配置和nexus的代理配置，这些内容都需要有文档。请补齐并发布到boat-house文档库中

**Comment by smallidea** [comment]
> @smallidea 资源本地化，Nginix配置和nexus的代理配置，这些内容都需要有文档。请补齐并发布到boat-house文档库中

+ 资源本地化，操作很简单，所以只是在前端库根目录的readme.md中做了说明，并没有单独开一个markdown
 [文档](https://github.com/idcf-boat-house/boat-house-frontend/blob/master/README.md)
![image](https://user-images.githubusercontent.com/7962463/87270411-980fcc00-c502-11ea-8fc7-2355dfeb7b77.png)

+ nginx [文档](https://github.com/idcf-boat-house/boat-house-infrastructure/blob/master/environments/nginx/readme.md)
+ nexus [文档](https://github.com/idcf-boat-house/boat-house/blob/master/docs/quick-start/guide/nexus/readme.md)

**Comment by smallidea** [comment]
>  jenkins build里面有报错信息 @smallidea

这个是spring boot编译过程中的debug信息，比如 

>  _Did not match:
@ConditionalOnClass did not find required classes 'com.github.benmanes.caffeine.cache.Caffeine', 'org.springframework.cache.caffeine.CaffeineCacheManager' (OnClassCondition)_

都是 “Negative matches” 的一部分，并不影响运行。

> _Positive matches：@Conditional条件为真，配置类被Spring容器加载。
Negative matches: @Conditional条件为假，配置类未被Spring容器加载。
Exclusions： 应用端明确排除加载配置
Unconditional classes： 自动配置类不包含任何类级别的条件，也就是说，类始终会被自动加载。_

@ups216 @liminany
