### ISSUE TITLE
作为测试人员，需要系统能够支持Jmeter接口测试，以便于快速完成繁琐工作，大幅提升工作效率，避免重复工作。

### ISSUE THREAD

**Issue by CadenGjy** [idcf-boat-house/boat-house#34]
AC:

1. 包含至少一组测试用例（增删改查），每个用例可以独立运行。

2. 需要包含功能测试、异常测试、边界测试等场景。

2. 流水线中包含Jmeter执行接口测试的步骤。

3. 流水线能获取到Jmeter执行接口测试的结果并加载到页面中。

**Comment by elegant1998** [comment]
验收标准AC

1. 可运行的Jmeter
2. 一个测试用例，可以验收对接口的测试
