### ISSUE TITLE
作为测试人员，需要系统能够支持Postman接口测试，以便于快速完成繁琐工作，大幅提升工作效率，避免重复工作。

### ISSUE THREAD

**Issue by zhouwenyang** [idcf-boat-house/boat-house#42]

**Comment by elegant1998** [comment]
验收标准AC：
能够支持任何类型的http请求，支持GET/PUT/POST/DELETE等方法。
可以直接填写URL，header，body等就可以发送一个请求
可以在浏览器中直接使用插件
能够跟jenkins集成，从而把接口测试纳入到持续集成CI中

**Comment by zlweicoder** [comment]
已拆分为两个issue:
 作为测试人员，需要系统能够支持Postman接口测试，以便于快速完成繁琐工作，大幅提升工作效率，避免重复工作
https://github.com/idcf-boat-house/boat-house/issues/120
 作为测试人员，我希望Jenkins能够集成Postman进行接口测试，以便在流水线执行完毕后能够看到测试结果。
https://github.com/idcf-boat-house/boat-house/issues/121
关闭此issue
