### ISSUE TITLE
作为移动团队，我希望可以有APP程序（MVP版本），以便配置支撑APP的流水线

### ISSUE THREAD

**Issue by zhouwenyang** [idcf-boat-house/boat-house#82]
AC：

1. 完成一个初级的MVP版本，可以只有一个简单的页面，主要是为了支撑流水线的搭建。

2. 页面上的内容要与BoatHouse点餐系统有关系。

2. MVP版本的APP能够发布安装到测试机器/PC模拟机器中。

**Comment by dengyakui** [comment]
可以搞个微信小程序
